//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class About {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal About() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.About", typeof(About).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư ngỏ.
        /// </summary>
        public static string Letter {
            get {
                return ResourceManager.GetString("Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lời chào của lãnh đạo.
        /// </summary>
        public static string Letter0 {
            get {
                return ResourceManager.GetString("Letter0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kính gửi Qúi khách hàng..
        /// </summary>
        public static string Letter1 {
            get {
                return ResourceManager.GetString("Letter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trước hết, công ty chúng tôi xin trân trọng cảm ơn sự ủng hộ của quí khách hàng trong suốt 26 năm qua..
        /// </summary>
        public static string Letter2 {
            get {
                return ResourceManager.GetString("Letter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến nay, công ty chúng tôi đã đạt được nhiều tiến bộ vượt bậc. Nhìn lại quãng đường đi qua, chúng tôi nhận ra rằng trong mọi thành công của công ty, đều có sự hợp tác của quí khách hàng..
        /// </summary>
        public static string Letter3 {
            get {
                return ResourceManager.GetString("Letter3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng ta có thể nhắc tên những bạn hàng đã cùng với chúng ta xây dựng nên thương hiệu: Công ty TNHH Xây Dựng và Xử Lý Môi Trường Đại Minh: BIG C Việt Nam, Bitexco, Cảng Container Hiệp Phước, Cảng VICT Tân Thuận, Công ty cấp thoát nước Lâm Đồng, Bệnh viện Hội an, Công ty CP Du Lịch Kỳ Vân và rất nhiều khách hàng thân thiết nữa..
        /// </summary>
        public static string Letter4 {
            get {
                return ResourceManager.GetString("Letter4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nay, tiếp bước các bậc tiền bối, thế hệ mới của công ty chúng tôi vững tâm niệm một quan điểm: Chất lượng môi trường là tiên quyết..
        /// </summary>
        public static string Letter5 {
            get {
                return ResourceManager.GetString("Letter5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi xin cam kết, nếu được quí khách hàng – dù mới hay cũ – tin tưởng giao nhiệm vụ, sẽ tận tâm hoàn thành các dự án được giao vì Môi trường, Chất lượng và Tiến độ với chi phí hợp lý..
        /// </summary>
        public static string Letter6 {
            get {
                return ResourceManager.GetString("Letter6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay mặt Ban TGĐ Công ty.
        /// </summary>
        public static string Lettersign {
            get {
                return ResourceManager.GetString("Lettersign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Nguyễn Khải Minh).
        /// </summary>
        public static string Lettersign1 {
            get {
                return ResourceManager.GetString("Lettersign1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu sơ lược về công ty Damifa.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử hình thành và phát triển.
        /// </summary>
        public static string Summary0 {
            get {
                return ResourceManager.GetString("Summary0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAMIFA, với kinh nghiệm 26 năm trong lĩnh vực xử lý nước, đã thực hiện thành công hơn 100 dự án lớn, nhỏ tại Việt Nam. Là doanh nghiệp tư nhân đi đầu trong lĩnh vực cấp thoát nước và xử lý môi trường..
        /// </summary>
        public static string Summary1 {
            get {
                return ResourceManager.GetString("Summary1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 1992 - DAMIFACo., Ltd Công ty Đại Minh - DAMIFA Co.,Ltd thành lập từ năm 1992. DAMIFA Co.,LTD - Công ty TNHH Xây Dựng và Xử Lý Môi Trường ĐẠI Minh được chính thức thành lập năm 1992, Giấy phép thành lập số 2084/GP-UB, cho đến nay đã hình một đội ngũ có kinh nghiệm trong hoạt động thiết kế và thi công các công trình thuộc lĩnh vực cấp thoát nước, xử lý môi trường..
        /// </summary>
        public static string Summary2 {
            get {
                return ResourceManager.GetString("Summary2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 1995 - DAMIFA là hội viên chính thức của Hội Cấp Thoát Nước Việt Nam (VWSA)..
        /// </summary>
        public static string Summary3 {
            get {
                return ResourceManager.GetString("Summary3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 1996 - DAMIFA là thành viên trong Hội đồng quản trị của công ty liên doanh IDE-DAMIFA(IDE ASIE) chuyên ngành tư vấn, thiết kế, cấp thoát nước và bảo vệ môi trường..
        /// </summary>
        public static string Summary4 {
            get {
                return ResourceManager.GetString("Summary4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 1996 - 2000 DAMIFA đã ký kết các hợp đồng đại lý, hợp tác kinh doanh và nhận được hỗ trợ về mặt kỹ thuật cũng như về thiết bị từ các công ty Salmson, Eversoft, Dosatron, IDE Ingénierie… của Pháp và Châu Âu..
        /// </summary>
        public static string Summary5 {
            get {
                return ResourceManager.GetString("Summary5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2014 - DAMIFA được sát nhập vào công ty CP ICEI, và trở thành 1 thành viên của công ty ICEI..
        /// </summary>
        public static string Summary6 {
            get {
                return ResourceManager.GetString("Summary6", resourceCulture);
            }
        }
    }
}
