//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Carousel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Carousel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Carousel", typeof(Carousel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÔNG TY TNHH XÂY DỰNG VÀ XỬ LÝ MÔI TRƯỜNG.
        /// </summary>
        public static string first {
            get {
                return ResourceManager.GetString("first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐẠI MINH - DAMIFA CO. LTD.
        /// </summary>
        public static string first1 {
            get {
                return ResourceManager.GetString("first1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23 năm kinh nghiệm trong lĩnh vực xử lý nước,.
        /// </summary>
        public static string first2 {
            get {
                return ResourceManager.GetString("first2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tiên phong trong lĩnh vực cấp thoát nước và xử lý môi trường.
        /// </summary>
        public static string first3 {
            get {
                return ResourceManager.GetString("first3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÔNG NGHỆ XỬ LÝ NƯỚC CẤP.
        /// </summary>
        public static string second {
            get {
                return ResourceManager.GetString("second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Cung cấp và xây dựng.
        /// </summary>
        public static string second1 {
            get {
                return ResourceManager.GetString("second1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hệ thống cấp nước cho công trình-.
        /// </summary>
        public static string second2 {
            get {
                return ResourceManager.GetString("second2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÔNG NGHỆ XỬ LÝ NƯỚC THẢI.
        /// </summary>
        public static string third {
            get {
                return ResourceManager.GetString("third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Tư vấn, khảo sát, thiết kế và thi công.
        /// </summary>
        public static string third1 {
            get {
                return ResourceManager.GetString("third1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to các trạm xử lý nước thải đô thị -.
        /// </summary>
        public static string third2 {
            get {
                return ResourceManager.GetString("third2", resourceCulture);
            }
        }
    }
}
