//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lĩnh vực đang hoạt động.
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp tác, hỗ trợ và nghiên cứu cùng với các công ty trong và ngoài nước trong lĩnh vực bảo vệ môi trường..
        /// </summary>
        public static string Field1 {
            get {
                return ResourceManager.GetString("Field1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thi công công trình..
        /// </summary>
        public static string Field2 {
            get {
                return ResourceManager.GetString("Field2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xây dựng và lắp đặt các hệ thống xử lý nước..
        /// </summary>
        public static string Field3 {
            get {
                return ResourceManager.GetString("Field3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển giao công nghệ chuyên ngành xử lý nước và môi trường..
        /// </summary>
        public static string Field4 {
            get {
                return ResourceManager.GetString("Field4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoạch định và đánh giá các thiết bị xử lý môi trường..
        /// </summary>
        public static string Field5 {
            get {
                return ResourceManager.GetString("Field5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cung cấp bơm các loại và các thiết bị xử lý môi trường..
        /// </summary>
        public static string Field6 {
            get {
                return ResourceManager.GetString("Field6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức sự kiện.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thủ tướng mời gọi các dự án bảo vệ môi trường đến Việt Nam.
        /// </summary>
        public static string News1 {
            get {
                return ResourceManager.GetString("News1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trước 1.500 đại biểu quốc tế, Thủ tướng khẳng định Việt Nam không đánh đổi môi trường lấy phát triển kinh tế..
        /// </summary>
        public static string News1detail {
            get {
                return ResourceManager.GetString("News1detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành phố đầu tiên trên thế giới tận dụng nước thải để vừa tái chế ra nước sạch, vừa cung cấp điện cho người dân.
        /// </summary>
        public static string News2 {
            get {
                return ResourceManager.GetString("News2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Một thành phố ở Đan Mạch đầu tư hệ thống sản xuất điện từ nước thải sinh hoạt để đưa nước tới các hộ gia đình..
        /// </summary>
        public static string News2detail {
            get {
                return ResourceManager.GetString("News2detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tác chiến lược.
        /// </summary>
        public static string Partner {
            get {
                return ResourceManager.GetString("Partner", resourceCulture);
            }
        }
    }
}
