//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Layout", typeof(Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới Thiệu.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home/About.
        /// </summary>
        public static string Aboutlink {
            get {
                return ResourceManager.GetString("Aboutlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy kết nối với chúng tôi.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên Hệ.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại Minh - Damifa Co. Ltd..
        /// </summary>
        public static string Contact1 {
            get {
                return ResourceManager.GetString("Contact1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Văn Phòng chính.
        /// </summary>
        public static string Contact2 {
            get {
                return ResourceManager.GetString("Contact2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ: 60/44 Quốc Lộ 13, P.26, Q.BT, TP.HCM..
        /// </summary>
        public static string Contact3 {
            get {
                return ResourceManager.GetString("Contact3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại: 084 (028) 3899 7567.
        /// </summary>
        public static string Contact4 {
            get {
                return ResourceManager.GetString("Contact4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax: +084 (028) 3899 7569.
        /// </summary>
        public static string Contact5 {
            get {
                return ResourceManager.GetString("Contact5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail: damifa@hcm.vnn.vn || daiminh@damifa.com.
        /// </summary>
        public static string Contact6 {
            get {
                return ResourceManager.GetString("Contact6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home/Contact.
        /// </summary>
        public static string Contactlink {
            get {
                return ResourceManager.GetString("Contactlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home/Index.
        /// </summary>
        public static string Indexlink {
            get {
                return ResourceManager.GetString("Indexlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin Tức.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home/Tintuc.
        /// </summary>
        public static string Newslink {
            get {
                return ResourceManager.GetString("Newslink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự Án.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home/DuAn.
        /// </summary>
        public static string Projectlink {
            get {
                return ResourceManager.GetString("Projectlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch Vụ.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home/Xulynuoccap.
        /// </summary>
        public static string ServiceSlink {
            get {
                return ResourceManager.GetString("ServiceSlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home/Xulynuocthai.
        /// </summary>
        public static string ServiceWlink {
            get {
                return ResourceManager.GetString("ServiceWlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công nghệ xử lí nước cấp.
        /// </summary>
        public static string SupTreatment {
            get {
                return ResourceManager.GetString("SupTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công nghệ xử lí nước thải.
        /// </summary>
        public static string WasteTreatment {
            get {
                return ResourceManager.GetString("WasteTreatment", resourceCulture);
            }
        }
    }
}
